version: '3.7'
services:
  nginx_1:
    image: nginx:1.21.6
    ports:
      - "8000:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
  
  nginx_2:
    image: nginx:1.21.6
    ports:
      - "8001:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html