version: '3.7'
services:
  nginx_1:
    build:
      context: ./
      dockerfile: Dockerfile 
    ports:
      - "8000:80"
    # volumes:
    #   - ./index.html:/usr/share/nginx/html/index.html
  
  nginx_2:
    build:
      context: ./
      dockerfile: Dockerfile 
    ports:
      - "8001:80"
    # volumes:
    #   - ./index.html:/usr/share/nginx/html/index.html