version: '3.7'
services:
  nginx_1:
    build:
      context: ./
      dockerfile: Dockerfile 
    ports:
      - "8000:80"
  
  nginx_2:
    build:
      context: ./
      dockerfile: Dockerfile 
    ports:
      - "8001:80"